# Jekyll 配置文件
title: "技术博客"
description: "Context Engineering and AI Development Blog"
baseurl: ""
url: "https://zhangxin15435.github.io/rss_autopost"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# RSS Feed 设置
feed:
  path: feed.xml
  posts_limit: 20

# 排除文件
exclude:
  - node_modules
  - package.json
  - README.md
  - src/

# 集合设置
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# 默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_excerpts: true
